domain: plantbasedbacon.xyz
records:
    - host: plantbasedbacon.xyz
      type: ALIAS
      ttl: 600
      content: pixie.porkbun.com
    - host: '*.plantbasedbacon.xyz'
      type: CNAME
      ttl: 600
      content: pixie.porkbun.com
