name: System tests

on:
  pull_request:
  schedule:
    - cron: '00 2 * * *'
  workflow_dispatch:

jobs:
  test:
    name: Run system tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: make test-system
        env:
          PORKBUN_API_KEY: ${{ secrets.PORKBUN_API_KEY }}
          PORKBUN_SECRET_KEY: ${{ secrets.PORKBUN_SECRET_KEY }}
